services:
  landing-page:
    build: .
    container_name: application
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks: 
      - my_network

  db:
    image: postgres:13
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network: