"""Create count table to store total visitors

Revision ID: 0880e824ec1e
Revises: 
Create Date: 2024-12-12 19:39:47.694136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0880e824ec1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("InSERT INTO count (id, count) VALUES (1, 0)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('count')
    # ### end Alembic commands ###
